### ISSUE TITLE
Thursday, March 19th, 2019

### ISSUE THREAD

**Issue by jackmcdade** [jackmcdade/statamic-giveaway#1]
Who do you think could use a [Statamic](https://statamic.com) license? Nominate them below with your reason why! If you don't know anyone, feel free to give a thumbs up to any of the nominations below. I'll pick the top one (or perhaps more if it's close or the reasons warm my heart) at the end of the day – somewhere around 6:30pm EST.

Be nice, do good! ❤️

**Comment by jcashatt** [comment]
Hey Jack, I’d love to be able to use one for my church, First Baptist Irmo. We’ve been using Webflow and the user roles are extremely limited, not to mention the ongoing costs of hosting with them and the monthly account subscription. It’s in the neighborhood of $55/mo! Plus, we are “locked in” until we have another solution, (preferably Statamic!) I believe the monthly subscription is money we could and should be using to minister to people instead.

**Comment by driftingly** [comment]
There are so many people who come to mind in the Laravel community who are so deserving.  I'd like to nominate Victor Gonzalez who produces the Coder's Tape videos on YouTube.  These videos are really easy to follow and explain the concepts covered perfectly.

**Comment by nsouto** [comment]
@digitaldaph is working w/civic tech  to gather to make it easier to find community resources available in their neighbourhoods. There’s lots of help but it’s really hard to find.

**Comment by schmidtflo** [comment]
I would love to use Statamic for my fathers small start up, which he had to found after closing of the work site from his longstanding employment.

**Comment by amazzina** [comment]
My good friend Lizzie Perrin is an incredible woman who gave up a successful career in public administration to start her own business. She's done a lot of research on platforms and has settled on Statamic as the best choice. She's a working mom who sacrifices everything, including a high-paying job, to be an example of entrepreneurship for her son.

"Mog Creative is a small B2B digital agency with a lot of love to give. We’re in the business of working with people—not templates—so we conduct thorough market research and guarantee unique marketing strategies meant exactly for you. We’re equipped to take on projects of any size. So whether you need a full website re-design, or a single blog post, we promise to provide the best service while never going over budget—ever. Let Mog help you build your brand and grow your bottom line."

**Comment by lizzieperrin** [comment]
@amazzina THANK YOU!!! ❤️❤️❤️❤️

**Comment by lizzieperrin** [comment]
Well OBVIOUSLY I'm going to hit back at my bestie Alyssa Mazzina. She gave up her freelance site a while back and I know she was really proud of it. She's also planning to take your design course, so having this license will give her the opportunity to put her new skills in action! 

Additionally, she's a boss-lady-mom-doer-of-all-things and she inspires me constantly. She deserves this!

**Comment by jackmcdade** [comment]
Can't pick, so all of these people and causes get a license. I'm closing this thread and will in touch with all of you after I have some dinner with the family. 😊
